### ISSUE TITLE
Invalid processing of the input text

### ISSUE THREAD

**Issue by mudrd8mz** [safatshahin-dev/moodle-mod_debate#1]
When the input text is not a plain text (as dictated by `PARAM_TEXT` parameter) then the external function throws fatal error:

> Invalid parameter value detected (Invalid external api parameter: the value is "<h", the server was expecting "text" type): Invalid external api parameter: the value is "<h", the server was expecting "text" type

![image](https://user-images.githubusercontent.com/85831/106885432-da893800-66e2-11eb-89f5-3f6a6b7fee68.png)

Texts like this should be probably `PARAM_RAW` and be correctly processed upon output.

**Comment by safatshahin** [comment]
it's a mistake I make very often, made them param raw now. This error was coming find_debate_reponse, that already has a validation, so making it raw resolved it. I didn't restrict or filter in the add API while users add responses considering IT student might debate something with code or frond end stuff, as that's what I did a lot while studying in monash.
Thanks a lot for finding this.
