### ISSUE TITLE
enabeling group mode 

### ISSUE THREAD

**Issue by Dag-DE** [safatshahin-dev/moodle-mod_debate#12]
In a later version, working in groups will be fine ;-)

**Comment by safatshahin** [comment]
Yes good point, I have the plan of creating teams inside the activity, will address this in the next release, expecting to implement it within the next couple of weeks. Please check the link for the progress tracking:
https://trello.com/b/7nep6sSF/moodle-debate-plugin

**Comment by safatshahin** [comment]
Hi @Dag-EU, I have released the teams feature which works with groups, please have a look now. Closing this ticket.
