### ISSUE TITLE
tranlated strings

### ISSUE THREAD

**Issue by bhavel** [safatshahin-dev/moodle-mod_debate#16]
Ive translated debate to cs, but some string are use wrog, eg. "Either the edit mode is active or no more response is allowed".
Tnx

**Comment by safatshahin** [comment]
hi @bhavel , i will identify those add them to the language strings with the release soon. please also share the translation in git, it will help the community using that language.
I have some new components added to the plugin, please use the debate_teams branch instead.

**Comment by safatshahin** [comment]
hi @bhavel I have checked the string and its in the language pack, when you say wrong, can you please specify what you mean? its the text when the edit mode is on or no more response is allowed for the user.

**Comment by bhavel** [comment]
![debate](https://user-images.githubusercontent.com/1582691/111914943-61685900-8a74-11eb-9ba5-eb3119a71ca8.png)
Red strings are wrong, green are ok.

**Comment by leofreitas** [comment]
Hi @bhavel and @safatshahin, please also share the translation in [central repository of Moodle](https://lang.moodle.org). It tracks the addition of English strings into Moodle code (core and plugins), gathers translations, handles common translation tasks and generates language packages to be deployed on Moodle servers. It will help the community using this.

**Comment by bhavel** [comment]
My strings was translated by AMOS [https://moodle.org/plugins/translations.php?plugin=mod_debate](https://moodle.org/plugins/translations.php?plugin=mod_debate)

**Comment by safatshahin** [comment]
hi @bhavel, I might have identified the issue which looks like the string rendered from jquery is not getting the translated string, I will have a look and update you in this.

**Comment by bhavel** [comment]
After updating language packs seems modul debate OK.

**Comment by safatshahin** [comment]
that's great, closing this ticket now.
