### ISSUE TITLE
Incorrect namespace

### ISSUE THREAD

**Issue by mudrd8mz** [safatshahin-dev/moodle-mod_debate#2]
The class in `classes/webservice/debate_data.php` actually implements https://docs.moodle.org/dev/Core_APIs#External_functions_API_.28external.29 and not https://docs.moodle.org/dev/Core_APIs#Web_services_API_.28webservice.29

The correct namespace should be `mod_debate\external`

**Comment by safatshahin** [comment]
resolved it in the latest commit to the main branch.
