### ISSUE TITLE
String identifier 'search:activity' missing

### ISSUE THREAD

**Issue by mattgig** [safatshahin-dev/moodle-mod_debate#21]
I get a warning in my installation (developer mode one) that the string identifier 'search:activity" was missing. Is is it possible that the string identifier "search_activity" should be called?

**Comment by safatshahin** [comment]
Hi @mattgig 
Thank you for reporting this. I am currently looking into this. I will be releasing the fix by the end of July or early August.
Cheers!

**Comment by safatshahin** [comment]
Hi @mattgig 
Thank your form reporting the issue. I has been resolved in the latest release.
