### ISSUE TITLE
As I type, the "Possible matching responses" section causes "jumping" of the page content footer

### ISSUE THREAD

**Issue by mudrd8mz** [safatshahin-dev/moodle-mod_debate#4]
I don't fully understand what that feature is for. But I noticed that when I pause typing, the AJAX loaded content is rendered but it causes not so nice page "jumps" or flickering (as the section disappears and appears again).

**Comment by mudrd8mz** [comment]
Trying to show the section that gets collapses and expanded on re-rendering the section.

![image](https://user-images.githubusercontent.com/85831/107117091-08ec4c00-6878-11eb-901a-59b957faae28.png)

**Comment by safatshahin** [comment]
Hi @mudrd8mz, this feature actually renders the possible matching responses according to the words you typed. It checks after you stop typing 700ms, and gets you all the possible matching responses in the same debate to help you decide if your response is matching with someone else's or you are typing the same thing. It's happening realtime from the js and it sends the ajax req to get the possible matching data and renders through a mustache.

For example, in this screenshot, there are two previous responses, so the response I just typed, has got some matching words, so it's listing those to help the user if the response is still appropriate or not. This feature is helpful when you have a lot of responses already in the same debate.
![image](https://user-images.githubusercontent.com/55496911/107453541-46feae00-6b9f-11eb-987e-de71504b7da6.png)

**Comment by safatshahin** [comment]
Closing this ticket as there is no further issue found.
