### ISSUE TITLE
Activity completion requirement to include "post at least one argument"

### ISSUE THREAD

**Issue by marycooch** [safatshahin-dev/moodle-mod_debate#6]
Similar to Forums for example, activity completion would work better if the student is required to add at least one argument. At the moment it is only "require view".

**Comment by safatshahin** [comment]
Hi mary, absolutely want to implement as soon as possible, started looking into it, hoping to get it done within next couple of days. thanks a lot.

**Comment by safatshahin** [comment]
Hi @marycooch, I am almost done implementing this feature, which triggers a completion as soon as the condition of the number of responses added from a user. 
I just wanted to discuss a quick point about deleting responses, for an example, if a user adds two responses and according to the condition, the user is marked as complete for this debate activity. Now, if the user deletes a response, what do you think we should do in that case? 
So far I thought of locking the deletion if the activity is completed for the user, what do you think?

**Comment by marycooch** [comment]
That is a tricky one -with a Forum activity for example, if two posts are required and the student posts twice, the activity is marked as complete - but if the student then goes back and deletes one of the posts, the activity reverts back to not complete. Is this a possibility? I understand the idea of locking it so they cannot delete a response, when they have added the correct number for completion but what if they make a genuine mistake?

**Comment by safatshahin** [comment]
Yes, I can do it as the forum does, it updates the status of the completion to COMPLETION_INCOMPLETE or 0 while a forum post is deleted.

**Comment by marycooch** [comment]
That sounds like the best option!

**Comment by safatshahin** [comment]
Hi @marycooch, thanks for your help in this. I have released this feature, please have a look here:
https://moodle.org/plugins/pluginversion.php?id=23416

**Comment by safatshahin** [comment]
Hi @marycooch just replying here regarding the post as I could not reply back to your message in moodle.org because of moodle capability and could not find any other communication channel.
Please go ahead with the post and email me here for any information: safatshahin@gmail.com

**Comment by marycooch** [comment]
Great thanks!
